config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  root to: 'pages#index'

  resources :sessions, only: [:update]
  resources :classrooms

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      
      if user.role?(:admin)
        can :manage, :all
      elsif user.role?(:teacher)
        can :read, :all
      elsif user.role?(:student)
        can :read, Classroom
      elsif user.role?(:guest)
      end
    #
    # The first argument to `can` is the action you are giving the student
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  ROLES = {0 => :guest, 1 => :student, 2 => :teacher, 3 => :admin}

  attr_reader :role

  def initialize(role_id = 0)
    @role = ROLES.has_key?(role_id.to_i) ? ROLES[role_id.to_i] : ROLES[0]
  end

  def role?(role_name)
    role == role_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    User.new(session[:id])
  end

  helper_method :current_user

  rescue_from CanCan::AccessDenied do |exception|
    flash[:warning] = exception.message
    redirect_to root_path
  end
  
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  def index 
    @classrooms = Classroom.all
    authorize! :read, @classrooms
  end

  def new 
    @classrooms = Classroom.new
    authorize! :index, @classrooms
  end

  def create
    @classroom = Classroom.new(classroom_params)
    if @classroom.save
      flash[:success] = "Porject was saved!"
      redirect_to root_path
    else
      render "new"
    end
    authorize! :create, @classroom
  end

  private

  def classroom_params
    params.require(:classroom).permit(:title)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def update
    id = params[:id].to_i
    session[:id] = User::ROLES.has_key?(id) ? id : 0
    flash[:success] = "Your new role #{User::ROLES[id]} was set!"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/classrooms/_form.html.erb
<%= form_for @classroom do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <%= f.submit 'Post', class: 'btn btn-primary' %>
  <% end %>

app/views/classrooms/index.html.erb
<div class="page-header"><h1>Classrooms</h1>

<ul class="nav navbar-nav">
  <% if can? :create, Classroom %>
    <li><%= link_to 'Add Classroom', new_classroom_path %></li>
  <% end %>
</ul>
</div>

<% @classrooms.each do |classroom| %>
  <div class="well well-sm">
    <h2><%= classroom.title %></h2>
  </div>
<% end %>

app/views/classrooms/new.html.erb
<div class="page-header"><h1>New Classroom</h1></div>

<%= render 'form' %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'iCan', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
      </ul>

      <ul class="nav navbar-nav pull-right">
        <li class="dropdown">
          <a class="dropdown-toggle" aria-expanded="false" role="button" data-toggle="dropdown" href="#">
            Role
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <% User::ROLES.each do |k, v| %>
              <li>
                <%= link_to session_path(k), method: :patch do %>
                  <%= v %>
                  <% if v == current_user.role %>
                    <small class="text-muted">(current)</small>
                  <% end %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ICan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
</head>
<body>

<%= render partial: "layouts/navbar" %>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
  <%= yield %>
</div>

<div class="page-header"><h1>Welcome!</h1></div>

<% if can? :index, Classroom %>
  <%= link_to 'Classrooms', classrooms_path, class: 'btn btn-lg btn-primary' %>
<% end %>